#!/bin/bash
#
# Configure dual-monitors.
# Left monitor landscape, right monitor portrait rotated 90 degrees clockwise.
/usr/bin/xrandr --output HDMI-1 --mode 1920x1080 --rotate normal \
  --output HDMI-2 --mode 1920x1080 --right-of HDMI-1 --rotate left

